### PR TITLE
Default both linting thresholds to 0.

### LINKED ISSUE #361: Lint option -L should fail test if any linting problems are found
Not sure what's the story with all the --lint extra flags but the default should be the strict case.

### PR DESCRIPTION
**Pull request by Marsup**
Fixes #361.

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
maybe add some info in the docs that when linting is enabled it will fail the tests if linting warnings/errors are found

**Comment by Marsup** [comment]
Sort of done.

**Comment by AdriVanHoudt** [comment]
hmm that only suggest that when not provided a value it defaults to 0, it should really say that enabling linting will result in enabling those options

**Comment by Marsup** [comment]
That's implied by "defaults to".

**Comment by AdriVanHoudt** [comment]
I know but it could be read as 'defaults to 0 if the option is used but no value is specified'. Maybe nitpicking but just my thought

**Comment by Marsup** [comment]
We'll see if @geek wants a better wording, it's clear enough for me.

**Comment by AdriVanHoudt** [comment]
:+1:

**Pull request merged**
