### PR TITLE
Fix coverage on loop labels. Fixes #355.

### LINKED ISSUE #355: Error when running lab with coverage on babel compiled code
So I have a bit of code compiled with babel and not sure if this is a lab or babel issue so will cross link issues. Lab runs fine with out coverage but get this error with coverage enabled:
```
./dist/test/couchbase/doc.js',5);continue _function;
                                                                    ^^^^^^^^^
SyntaxError: Undefined label '_function'
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.require.extensions.(anonymous function) [as .js] (./node_modules/lab/lib/coverage.js:29:36)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at ./node_modules/lab/lib/cli.js:105:23
    at Array.forEach (native)
    at Object.internals.traverse (./node_modules/lab/lib/cli.js:101:19)
    at Object.exports.run (./node_modules/lab/lib/cli.js:50:29)
    at Object.<anonymous> (./node_modules/lab/bin/lab:3:23)
    at Module._compile (module.js:431:26)
    at Object.Module._extensions..js (module.js:449:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:472:10)
    at startup (node.js:124:18)
    at node.js:959:3
```
Here is the compiled source
```
var _get = function get(_x2, _x3, _x4) { var _again = true; _function: while (_again) { desc = parent = getter = undefined; _again = false; var object = _x2,
    property = _x3,
    receiver = _x4; var desc = Object.getOwnPropertyDescriptor(object, property); if (desc === undefined) { var parent = Object.getPrototypeOf(object); if (parent === null) { return undefined; } else { _x2 = parent; _x3 = property; _x4 = receiver; _again = true; continue _function; } } else if ("value" in desc) { return desc.value; } else { var getter = desc.get; if (getter === undefined) { return undefined; } return getter.call(receiver); } } };
```

### PR DESCRIPTION
**Pull request by Marsup**

### CODE REVIEW

**Comment by Marsup** [comment]
@geek it seems travis is very tired right now, I can't see any of those errors on any environment.

**Comment by Marsup** [comment]
OK after re-installing my deps it seems to be a breaking change in `diff`. Fixing.

**Comment by Marsup** [comment]
@geek Ready to go.

**Comment by geek** [comment]
yay

**Comment by geek** [comment]
Thanks @Marsup, I had just ran into this issue locally :)

**Pull request merged**
