### PR TITLE
Helpful message when path not found

### PR DESCRIPTION
**Pull request by jtlapp**
This is a PR for issue #759. Also appended LFs to error messages that `cli.js` outputs to `options.output` so that the shell prompt lands on the following line.

### CODE REVIEW

**Comment by jtlapp** [comment]
A decision still needs to be made about the appropriate exit code. If it should be zero, then the reporter test case cited in #759 will fail (and apparently for the wrong reasons).

**Comment by jtlapp** [comment]
An alternative solution would pull the missing file name out of the error message, so that lab would properly report files in subdirectories that get deleted in the middle of a test run (under very specific circumstances). I was less comfortable with creating a dependency on the form of the error message. The only other option adds complexity to the `traverse()` function.

The present implementation seemed like a reasonable compromise of probability and simplicity.

**Comment by jtlapp** [comment]
Hold on. I thought of a simple fix that shows even files deleted mid-test. Mod coming...

**Comment by jtlapp** [comment]
That should do it.

**Comment by geek** [comment]
@jtlapp thanks, this will be included in the next release.

**Pull request merged**
