### PR TITLE
Use no-shadow lint rule

### LINKED ISSUE #369: no-catch-shadow
https://jslinterrors.com/value-of-a-may-be-overwritten-in-ie8

Why do we care?!

### PR DESCRIPTION
**Pull request by geek**
Remove IE8 rule and use broader no-shadow with a warning

Fixes #369

### CODE REVIEW

**Comment by hueniverse** [comment]
What's with all the `forEach` replacements?

**Comment by geek** [comment]
@hueniverse I was wondering what you would say about those :) 

We were using them elsewhere in the code, and I wanted to be a little more consistent and contain the variables in the scope a little more.

**Comment by hueniverse** [comment]
Ok. Was just unrelated to the issue being fixed.

**Comment by hueniverse** [comment]
What's with all the `done` -> `finished`?

**Comment by geek** [comment]
In the tests that was to avoid shadowing `done`, however, it may be more appropriate as `next`... do you have a preference?

**Comment by hueniverse** [comment]
`done` should be the actual test where `next` or `testDone` should be the code being tested.

**Comment by geek** [comment]
@hueniverse I updated the test script tests to use `testDone` instead of `finished`, see what you think.

**Pull request merged**
