### PR TITLE
add URL and URLSearchParams to global variables

### PR DESCRIPTION
**Pull request by mcollina**
Those will be globals in Node 10 (and current are in node master).
I'm sending this PR early because shot is currently failing on CITGM.

Ref https://github.com/hapijs/shot/pull/91.

### CODE REVIEW

**Comment by Marsup** [comment]
Should probably be added like in L92-115.

**Comment by mcollina** [comment]
Done.

**Comment by mcollina** [comment]
I do not know why that test is failing (see https://travis-ci.org/hapijs/lab/jobs/339389589), I think that test is flaky.

**Comment by Marsup** [comment]
Can't get a flake locally but apparently travis can indeed.

**Comment by geek** [comment]
Thanks for the help @mcollina

**Comment by mcollina** [comment]
No worries, I'm trying to get CITGM greener, and this was on the list.

**Pull request merged**
