### PR TITLE
Add --bail support

### LINKED ISSUE #214: Stop Tests On First Failure
The idea would be to add a command line flag to lab that would cause the set of test cases to stop on first failure and show the output of that failed test instead of having to wait for all tests to complete and then see the output.

You could also make it an option that it shows the reason for the test failure in line with the verbose output so you can see the reason for the failure as the tests continue to run so you can determine if tests are failing due to the same issue. Again without waiting for the entire set of tests to complete.

### PR DESCRIPTION
**Pull request by geek**
Closes #214

### CODE REVIEW

**Comment by geek** [comment]
@Marsup thanks for the feedback, the PR is updated.

**Comment by Marsup** [comment]
Looks even simpler 👍

**Comment by lerouxb** [comment]
Great. Now can someone please do a release so I can use this? :)

**Comment by geek** [comment]
@lerouxb published!

**Pull request merged**
