### PR TITLE
Fix coverage of trailing function declaration

### PR DESCRIPTION
**Pull request by rluba**
Declaring a function after a return statement causes lab to report the declaration as "not covered".

The new test demonstrates the problem: The old coverage code incorrectly reports lines 14 and 21 of `test/coverage/trailing-function-declarations.js` as "not covered". The fix in 2ba2d72 solves this problem by excluding function declarations from tracking.

### CODE REVIEW

**Comment by rluba** [comment]
This PR will conflict with #520 because they both insert new tests at the same location in the test suite. Simply resolve it by arranging them in any order.

**Comment by geek** [comment]
@rluba PR #520 is now merged if you want to rebase this

**Comment by rluba** [comment]
@geek Thx, I’ve resolved the conflict.

**Comment by geek** [comment]
@rluba well done, looks great.

**Pull request merged**
