### PR TITLE
Linting update

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
* updates eslint to 0.22.x
    * added `lines-around-comment` and `object-curly-spacing` rules
* updates jslint to 0.9.x
* removed linting thresholds because they are default now
* linting test are more strict
* added container based travis as per https://github.com/hapijs/contrib/issues/30

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
Eslint 0.22.1 was just released so I'll update to that before you can merge

**Comment by Marsup** [comment]
I think we should ping @geek now that it's working :)

**Comment by AdriVanHoudt** [comment]
I bumped to eslint 0.22.x and added the new rules that applied to the styleguide
`lines-around-comment` however does not support `No empty line before when following { unless other rules require it` so atm it just forces the empty line (you could use `/* */`) if you want but styleguide forbids usage of that
Also `npm install` on iojs failed in tests not the tests themself

**Comment by geek** [comment]
I restarted the job.   Thanks for the help on this.

**Comment by AdriVanHoudt** [comment]
Tests are all passing and no problem!

**Comment by AdriVanHoudt** [comment]
You want me to squash the commits?

**Comment by AdriVanHoudt** [comment]
Is there anything needed from me to merge?

**Pull request merged**
