### PR TITLE
Add ESLint rule for blank line at beginning of function scope

### PR DESCRIPTION
**Pull request by cjihrig**
The rule causes warnings if the blank line is missing. Testing turned up a couple places where the blank line was missing in lab.

### CODE REVIEW

**Comment by Marsup** [comment]
:+1: Shouldn't we create a single module for all hapi-related rules ? One module per rule seems overkill.

**Comment by Marsup** [comment]
Also, wouldn't it be better to release it as an ESLint plugin ?

**Comment by cjihrig** [comment]
This was the only rule that @geek brought to my attention. What else is missing/not natively supported by ESLint?

**Comment by Marsup** [comment]
There were a few when I first implemented ESLint into lab, maybe it changed. I'll try to put up a list someday.

**Comment by AdriVanHoudt** [comment]
@cjihrig I love the rule! But can you make it into a plugin so I can use it in other projects (without using cli params) (see https://github.com/eslint/eslint/issues/2180)

**Comment by cjihrig** [comment]
I'll look into creating a plugin today.

**Comment by AdriVanHoudt** [comment]
@cjihrig cool thanks!

**Comment by cjihrig** [comment]
Converted to a plugin

**Comment by AdriVanHoudt** [comment]
@cjihrig thanks I will definitely use this!

**Comment by cjihrig** [comment]
:+1:

**Comment by tielur** [comment]
@geek I'm not familiar with the release cycle for lab, but when do you think this 5.5.2 will be pushed to npm?

**Pull request merged**
