### PR TITLE
Use a shareable config for ESLint

### PR DESCRIPTION
**Pull request by cjihrig**

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
:clap: now I can remove my `"extends": "./node_modules/lab/lib/linters/eslint/.eslintrc",` lines haha

**Comment by devinivy** [comment]
This is good news!!

**Comment by gergoerdosi** [comment]
I like this, better than extending `./node_modules/lab/lib/linters/eslint/.eslintrc`. However as this config is hapi specific (meaning the hapijs team sets the rules), shouldn't the module (`eslint-config-hapi`) be under the hapijs organization?

**Comment by AdriVanHoudt** [comment]
@cjihrig is there a way to put the config and plugin into 1 npm module?

**Comment by geek** [comment]
@cjihrig I do like the idea of the config being in the hapijs org

**Comment by cjihrig** [comment]
@AdriVanHoudt not currently. See the discussion in https://github.com/eslint/eslint/issues/2518 and https://github.com/eslint/eslint/issues/3458. I also find it frustrating, but it is what it is.

**Comment by AdriVanHoudt** [comment]
oh gawd...

**Pull request merged**
